export const FETCH_CATALOG = 'fetchCatalog'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const CHECK_AUTH = 'checkAuth'
export const RANK_USER_VIDEO = 'rankUserVideo'
export const FETCH_USER_VIDEOS = 'fetchUserVideos'
export const UPDATE_VIDEOS = 'updateVideos'
